"""fix ranking_entries missing columns

Revision ID: 2a2071bdf7df
Revises: f8e456351102
Create Date: 2026-03-10 09:11:46.446442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a2071bdf7df'
down_revision: Union[str, Sequence[str], None] = 'f8e456351102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only add missing columns to ranking_entries
    op.execute('ALTER TABLE competitions DROP COLUMN IF EXISTS class_id')
    op.execute('DROP TABLE IF EXISTS competition_classes CASCADE')
    op.execute('DROP TABLE IF EXISTS ranking_points CASCADE')
    op.execute('DROP TABLE IF EXISTS ranking_snapshots CASCADE')
    op.execute('DROP TABLE IF EXISTS federations CASCADE')
    op.execute('DROP TABLE IF EXISTS results CASCADE')

    op.execute('ALTER TABLE ranking_entries ADD COLUMN IF NOT EXISTS ranking_award_id UUID')
    op.execute('ALTER TABLE ranking_entries ADD COLUMN IF NOT EXISTS division_key VARCHAR(50)')
    op.execute('ALTER TABLE ranking_entries ADD COLUMN IF NOT EXISTS season_year INTEGER')
    op.execute('ALTER TABLE ranking_entries ADD COLUMN IF NOT EXISTS points NUMERIC(8,2)')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weight_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('weight_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('weight_categories', 'is_open_upper',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'REFEREE'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('team_rules', sa.Column('member_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('team_rules', sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('team_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('team_rules', 'athlete2_min_weight')
    op.drop_column('team_rules', 'athlete1_max_weight')
    op.drop_column('team_rules', 'athletes_per_team')
    op.add_column('seasons', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('seasons', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'seasons', type_='unique')
    op.alter_column('seasons', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'ACTIVE'::character varying"),
               existing_nullable=True)
    op.drop_column('seasons', 'created_at')
    op.drop_column('seasons', 'name')
    op.add_column('ranking_entries', sa.Column('p_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ranking_entries', sa.Column('q_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ranking_entries', sa.Column('points_awarded', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ranking_entries', sa.Column('competition_division_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('ranking_entries', sa.Column('formula_version', sa.VARCHAR(), server_default=sa.text("'1.2'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ranking_entries', type_='foreignkey')
    op.drop_constraint(None, 'ranking_entries', type_='foreignkey')
    op.drop_column('ranking_entries', 'points')
    op.drop_column('ranking_entries', 'season_year')
    op.drop_column('ranking_entries', 'division_key')
    op.drop_column('ranking_entries', 'ranking_award_id')
    op.add_column('ranking_awards', sa.Column('p_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ranking_awards', type_='foreignkey')
    op.drop_constraint(None, 'ranking_awards', type_='foreignkey')
    op.alter_column('ranking_awards', 'policy_version',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'1.2'::character varying"),
               existing_nullable=False)
    op.alter_column('ranking_awards', 's_awarded',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('ranking_awards', 'q_effective_applied',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('ranking_awards', 'p_value')
    op.add_column('protests', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('protests', sa.Column('athlete_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('protests', sa.Column('competition_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'protests', type_='foreignkey')
    op.alter_column('protests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'SUBMITTED'::character varying"),
               nullable=True)
    op.drop_column('protests', 'resolution')
    op.drop_column('protests', 'description')
    op.drop_column('protests', 'submitted_by')
    op.drop_column('protests', 'competition_division_id')
    op.alter_column('persons', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('persons', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(op.f('uq_participants_division_athlete'), 'participants', ['competition_division_id', 'athlete_id'], postgresql_nulls_not_distinct=False)
    op.add_column('overall_standings', sa.Column('tie_break_value', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('overall_standings', sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_overall_standings_division_participant', 'overall_standings', type_='unique')
    op.create_index(op.f('uq_overall_standings_division_participant'), 'overall_standings', ['competition_division_id', 'participant_id'], unique=True)
    op.alter_column('overall_standings', 'total_points',
               existing_type=sa.NUMERIC(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('overall_standings', 'created_at')
    op.drop_column('overall_standings', 'tiebreak_vector')
    op.drop_column('overall_standings', 'overall_place')
    op.drop_constraint('uq_discipline_standings_discipline_participant', 'discipline_standings', type_='unique')
    op.create_index(op.f('uq_discipline_standings_discipline_participant'), 'discipline_standings', ['competition_discipline_id', 'participant_id'], unique=True)
    op.alter_column('discipline_standings', 'points_for_discipline',
               existing_type=sa.NUMERIC(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'discipline_results', type_='foreignkey')
    op.drop_constraint(None, 'discipline_results', type_='foreignkey')
    op.create_foreign_key(op.f('discipline_results_participant_id_fkey'), 'discipline_results', 'participants', ['participant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('discipline_results_competition_discipline_id_fkey'), 'discipline_results', 'competition_disciplines', ['competition_discipline_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_discipline_result_discipline_participant'), 'discipline_results', ['competition_discipline_id', 'participant_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('discipline_results', 'status_flag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('countries_code_key'), 'countries', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('countries', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               nullable=False)
    op.add_column('competitions', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('competitions_class_id_fkey'), 'competitions', 'competition_classes', ['class_id'], ['id'])
    op.alter_column('competitions', 'date_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('competition_divisions', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'LIVE', 'RESULTS_VALIDATED', 'LOCKED', name='divisionstatus'),
               nullable=False)
    op.alter_column('competition_divisions', 'format',
               existing_type=postgresql.ENUM('CLASSIC', 'PARA', 'RELAY', 'TEAM_BATTLE', name='competitionformat'),
               nullable=False)
    op.alter_column('competition_disciplines', 'track_length_meters',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('competition_disciplines', 'order_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('athletes', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('athletes', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('competition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('athlete_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name=op.f('results_athlete_id_fkey')),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('results_competition_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('results_pkey'))
    )
    op.create_table('competition_classes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('coefficient_q', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('competition_classes_pkey'))
    )
    op.create_table('federations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('federations_country_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('federations_pkey'))
    )
    op.create_table('ranking_snapshots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('season_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('division_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('athlete_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('points', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ranking_snapshots_pkey'))
    )
    op.create_table('ranking_points',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('season_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('competition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('division_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('athlete_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('division_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('points', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name=op.f('ranking_points_athlete_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('ranking_points_competition_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['division_id'], ['competition_divisions.id'], name=op.f('ranking_points_division_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ranking_points_pkey')),
    sa.UniqueConstraint('competition_id', 'division_id', 'athlete_id', name=op.f('uq_ranking_points_comp_div_athlete'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('competition_division_snapshots')
    op.drop_table('competition_division_q')
    # ### end Alembic commands ###