"""add judge_id to matches

Revision ID: af39412a34fc
Revises: ddf0c5ea7915
Create Date: 2026-03-12 18:50:27.644131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af39412a34fc'
down_revision: Union[str, Sequence[str], None] = 'ddf0c5ea7915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_division_q',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_division_id', sa.UUID(), nullable=False),
    sa.Column('q_base', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('q_effective', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['competition_division_id'], ['competition_divisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_division_id')
    )
    op.create_table('competition_division_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition_division_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('q_effective', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_division_id'], ['competition_divisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('athletes', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('athletes', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('competition_disciplines', 'order_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('competition_disciplines', 'track_length_meters',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('competition_disciplines', 'is_final',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('competition_divisions', 'format',
               existing_type=postgresql.ENUM('CLASSIC', 'PARA', 'RELAY', 'TEAM_BATTLE', name='competitionformat'),
               nullable=True)
    op.alter_column('competition_divisions', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'LIVE', 'RESULTS_VALIDATED', 'LOCKED', name='divisionstatus'),
               nullable=True)
    op.alter_column('competition_divisions', 'age_group',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=True)
    op.alter_column('competition_sponsors', 'tier',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('competitions', 'date_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('competitions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('countries', 'code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               nullable=True)
    op.drop_constraint(op.f('countries_code_key'), 'countries', type_='unique')
    op.alter_column('discipline_results', 'status_flag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_discipline_result_discipline_participant'), 'discipline_results', type_='unique')
    op.drop_constraint(op.f('discipline_results_participant_id_fkey'), 'discipline_results', type_='foreignkey')
    op.drop_constraint(op.f('discipline_results_competition_discipline_id_fkey'), 'discipline_results', type_='foreignkey')
    op.create_foreign_key(None, 'discipline_results', 'participants', ['participant_id'], ['id'])
    op.create_foreign_key(None, 'discipline_results', 'competition_disciplines', ['competition_discipline_id'], ['id'])
    op.alter_column('discipline_standings', 'points_for_discipline',
               existing_type=sa.NUMERIC(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('uq_discipline_standings_discipline_participant'), table_name='discipline_standings')
    op.create_unique_constraint('uq_discipline_standings_discipline_participant', 'discipline_standings', ['competition_discipline_id', 'participant_id'])
    op.alter_column('match_discipline_results', 'result_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.add_column('matches', sa.Column('judge_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'matches', 'users', ['judge_id'], ['id'])
    op.alter_column('overall_standings', 'total_points',
               existing_type=sa.NUMERIC(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('overall_standings', 'overall_place',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('uq_overall_standings_division_participant'), table_name='overall_standings')
    op.create_unique_constraint('uq_overall_standings_division_participant', 'overall_standings', ['competition_division_id', 'participant_id'])
    op.drop_column('overall_standings', 'tie_break_value')
    op.drop_column('overall_standings', 'place')
    op.drop_constraint(op.f('uq_participants_division_athlete'), 'participants', type_='unique')
    op.alter_column('persons', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('persons', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('protests', sa.Column('competition_division_id', sa.UUID(), nullable=False))
    op.add_column('protests', sa.Column('submitted_by', sa.UUID(), nullable=False))
    op.add_column('protests', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('protests', sa.Column('resolution', sa.Text(), nullable=True))
    op.alter_column('protests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=False)
    op.create_foreign_key(None, 'protests', 'competition_divisions', ['competition_division_id'], ['id'], ondelete='CASCADE')
    op.drop_column('protests', 'athlete_id')
    op.drop_column('protests', 'competition_id')
    op.drop_column('protests', 'reason')
    op.add_column('ranking_awards', sa.Column('p_value', sa.Integer(), nullable=False))
    op.alter_column('ranking_awards', 'q_effective_applied',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=False)
    op.alter_column('ranking_awards', 's_awarded',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('ranking_awards', 'policy_version',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'ranking_awards', 'competition_divisions', ['competition_division_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ranking_awards', 'athletes', ['athlete_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ranking_awards', 'p_event')
    op.alter_column('ranking_entries', 'ranking_award_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ranking_entries', 'division_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ranking_entries', 'season_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ranking_entries', 'points',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    op.create_foreign_key(None, 'ranking_entries', 'ranking_awards', ['ranking_award_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ranking_entries', 'athletes', ['athlete_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ranking_entries', 'points_awarded')
    op.drop_column('ranking_entries', 'formula_version')
    op.drop_column('ranking_entries', 'competition_division_id')
    op.drop_column('ranking_entries', 'q_value')
    op.drop_column('ranking_entries', 'p_value')
    op.add_column('seasons', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('seasons', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('seasons', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.create_unique_constraint(None, 'seasons', ['year'])
    op.drop_column('seasons', 'end_date')
    op.drop_column('seasons', 'start_date')
    op.add_column('team_rules', sa.Column('athletes_per_team', sa.Integer(), nullable=False))
    op.add_column('team_rules', sa.Column('athlete1_max_weight', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('team_rules', sa.Column('athlete2_min_weight', sa.Numeric(precision=6, scale=2), nullable=True))
    op.alter_column('team_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('team_rules', 'member_rules')
    op.drop_column('team_rules', 'sort_order')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('weight_categories', 'is_open_upper',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('weight_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('weight_categories', 'age_group',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('weight_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weight_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('weight_categories', 'age_group',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'SENIOR'::character varying"),
               existing_nullable=False)
    op.alter_column('weight_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('weight_categories', 'is_open_upper',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'REFEREE'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('team_rules', sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('team_rules', sa.Column('member_rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('team_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('team_rules', 'athlete2_min_weight')
    op.drop_column('team_rules', 'athlete1_max_weight')
    op.drop_column('team_rules', 'athletes_per_team')
    op.add_column('seasons', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('seasons', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'seasons', type_='unique')
    op.alter_column('seasons', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'ACTIVE'::character varying"),
               existing_nullable=True)
    op.drop_column('seasons', 'created_at')
    op.drop_column('seasons', 'name')
    op.add_column('ranking_entries', sa.Column('p_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ranking_entries', sa.Column('q_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ranking_entries', sa.Column('competition_division_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('ranking_entries', sa.Column('formula_version', sa.VARCHAR(), server_default=sa.text("'1.2'::character varying"), autoincrement=False, nullable=False))
    op.add_column('ranking_entries', sa.Column('points_awarded', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ranking_entries', type_='foreignkey')
    op.drop_constraint(None, 'ranking_entries', type_='foreignkey')
    op.alter_column('ranking_entries', 'points',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
    op.alter_column('ranking_entries', 'season_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ranking_entries', 'division_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ranking_entries', 'ranking_award_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('ranking_awards', sa.Column('p_event', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ranking_awards', type_='foreignkey')
    op.drop_constraint(None, 'ranking_awards', type_='foreignkey')
    op.alter_column('ranking_awards', 'policy_version',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'1.2'::character varying"),
               existing_nullable=False)
    op.alter_column('ranking_awards', 's_awarded',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('ranking_awards', 'q_effective_applied',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('ranking_awards', 'p_value')
    op.add_column('protests', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('protests', sa.Column('competition_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('protests', sa.Column('athlete_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'protests', type_='foreignkey')
    op.alter_column('protests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'SUBMITTED'::character varying"),
               nullable=True)
    op.drop_column('protests', 'resolution')
    op.drop_column('protests', 'description')
    op.drop_column('protests', 'submitted_by')
    op.drop_column('protests', 'competition_division_id')
    op.alter_column('persons', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('persons', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(op.f('uq_participants_division_athlete'), 'participants', ['competition_division_id', 'athlete_id'], postgresql_nulls_not_distinct=False)
    op.add_column('overall_standings', sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('overall_standings', sa.Column('tie_break_value', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_overall_standings_division_participant', 'overall_standings', type_='unique')
    op.create_index(op.f('uq_overall_standings_division_participant'), 'overall_standings', ['competition_division_id', 'participant_id'], unique=True)
    op.alter_column('overall_standings', 'overall_place',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('overall_standings', 'total_points',
               existing_type=sa.NUMERIC(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'judge_id')
    op.alter_column('match_discipline_results', 'result_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'higher_wins'::character varying"),
               existing_nullable=True)
    op.drop_constraint('uq_discipline_standings_discipline_participant', 'discipline_standings', type_='unique')
    op.create_index(op.f('uq_discipline_standings_discipline_participant'), 'discipline_standings', ['competition_discipline_id', 'participant_id'], unique=True)
    op.alter_column('discipline_standings', 'points_for_discipline',
               existing_type=sa.NUMERIC(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'discipline_results', type_='foreignkey')
    op.drop_constraint(None, 'discipline_results', type_='foreignkey')
    op.create_foreign_key(op.f('discipline_results_competition_discipline_id_fkey'), 'discipline_results', 'competition_disciplines', ['competition_discipline_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('discipline_results_participant_id_fkey'), 'discipline_results', 'participants', ['participant_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_discipline_result_discipline_participant'), 'discipline_results', ['competition_discipline_id', 'participant_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('discipline_results', 'status_flag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('countries_code_key'), 'countries', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('countries', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('competitions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'DRAFT'::character varying"),
               existing_nullable=True)
    op.alter_column('competitions', 'date_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('competition_sponsors', 'tier',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'FREE'::character varying"),
               existing_nullable=True)
    op.alter_column('competition_divisions', 'age_group',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'SENIOR'::character varying"),
               existing_nullable=True)
    op.alter_column('competition_divisions', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'LIVE', 'RESULTS_VALIDATED', 'LOCKED', name='divisionstatus'),
               nullable=False)
    op.alter_column('competition_divisions', 'format',
               existing_type=postgresql.ENUM('CLASSIC', 'PARA', 'RELAY', 'TEAM_BATTLE', name='competitionformat'),
               nullable=False)
    op.alter_column('competition_disciplines', 'is_final',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('competition_disciplines', 'track_length_meters',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('competition_disciplines', 'order_no',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('athletes', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('athletes', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('competition_division_snapshots')
    op.drop_table('competition_division_q')
    # ### end Alembic commands ###