from db.base import Base

from models.athlete import Athlete
from models.season import Season
from models.competition import Competition
from models.competition_division import CompetitionDivision
from models.competition_discipline import CompetitionDiscipline
from models.participant import Participant
from models.discipline_result import DisciplineResult
from models.discipline_standing import DisciplineStanding
from models.overall_standing import OverallStanding
from models.protest import Protest
from models.competition_division_q import CompetitionDivisionQ
from models.competition_division_snapshot import CompetitionDivisionSnapshot
from models.ranking_award import RankingAward
from models.ranking_entry import RankingEntry
from models.weight_category import WeightCategory
from models.team_rule import TeamRule
from models.country import Country
from models.athlete_sponsor import AthleteSponsor
from models.judge import Judge
from models.judge_certificate import JudgeCertificate
from models.judge_competition import JudgeCompetition
from models.organizer import Organizer
from models.organizer_sponsor import OrganizerSponsor
from models.coach import Coach
from models.coach_certificate import CoachCertificate
from models.team import Team
from models.team_member import TeamMember
from models.team_sponsor import TeamSponsor
from models.competition_sponsor import CompetitionSponsor
from models.match import Match
from models.match_discipline_result import MatchDisciplineResult
from models.team_standing import TeamStanding
from models.asl_league import ASLLeague
from models.asl_division import ASLDivision
from models.asl_team_division import ASLTeamDivision
from models.asl_league import ASLLeague
from models.asl_division import ASLDivision
from models.asl_team_division import ASLTeamDivision
from models.person import Person
from models.user import User

target_metadata = Base.metadata